import { IcMFsea, IcMLand, IcMLcl, IcMAirport, IcMFland, IcMCustoms } from '@cogoport/icons-react';

const MAPPING = {
	freight: {
		tag      : 'FCL',
		icon     : IcMFsea,
		type     : 'sea',
		iconType : 'ship',
	},
	origin_local: {
		tag      : 'Local',
		icon     : IcMLand,
		type     : 'land',
		iconType : 'ship',
	},
	fcl_freight_local: {
		tag      : 'FCL Local',
		icon     : IcMLand,
		type     : 'land',
		iconType : 'ship',
	},
	lcl_freight_local: {
		tag      : 'LCL Local',
		icon     : IcMLand,
		type     : 'land',
		iconType : 'ship',
	},
	air_freight_local: {
		tag      : 'AIR Local',
		icon     : IcMLand,
		type     : 'land',
		iconType : 'ship',
	},
	destination_local: {
		tag      : 'Local',
		icon     : IcMLand,
		type     : 'land',
		iconType : 'ship',
	},
	fcl_freight: {
		tag      : 'FCL',
		icon     : IcMLand,
		type     : 'sea',
		iconType : 'ship',
	},
	lcl_freight: {
		tag      : 'LCL',
		icon     : IcMLcl,
		type     : 'sea',
		iconType : 'ship',
	},
	air_freight: {
		tag      : 'Air',
		icon     : IcMAirport,
		type     : 'air',
		iconType : 'air',
	},
	trailer_freight: {
		tag      : 'Trailer',
		icon     : IcMFland,
		type     : 'land',
		iconType : 'truck',
	},
	ftl_freight: {
		tag      : 'FTL',
		icon     : IcMFland,
		type     : 'land',
		iconType : 'truck',
	},
	ltl_freight: {
		tag      : 'LTL',
		icon     : IcMFland,
		type     : 'land',
		iconType : 'truck',
	},
	fcl_customs: {
		tag      : 'FCL Customs',
		icon     : 'ic-fcl',
		type     : 'customs',
		iconType : 'customs',
	},
	lcl_customs: {
		tag      : 'LCL Customs',
		icon     : IcMLcl,
		type     : 'customs',
		iconType : 'customs',
	},
	air_customs: {
		tag      : 'Air Customs',
		icon     : IcMAirport,
		type     : 'customs',
		iconType : 'customs',
	},
	haulage_freight: {
		tag      : 'Haulage',
		icon     : IcMFland,
		type     : 'land',
		iconType : 'train',
	},
	origin_trailer_freight: {
		tag      : 'Trailer',
		icon     : IcMFland,
		type     : 'land',
		iconType : 'truck',
	},
	destination_trailer_freight: {
		tag      : 'Trailer',
		icon     : IcMFland,
		type     : 'land',
		iconType : 'truck',
	},
	origin_ftl_freight: {
		tag      : 'FTL',
		icon     : IcMFland,
		type     : 'land',
		iconType : 'truck',
	},
	destination_ftl_freight: {
		tag      : 'FTL',
		icon     : IcMFland,
		type     : 'land',
		iconType : 'truck',
	},
	origin_ltl_freight: {
		tag      : 'LTL',
		icon     : IcMFland,
		type     : 'land',
		iconType : 'truck',
	},
	destination_ltl_freight: {
		tag      : 'LTL',
		icon     : IcMFland,
		type     : 'land',
		iconType : 'truck',
	},
	origin_fcl_customs: {
		tag      : 'FCL Customs',
		icon     : IcMCustoms,
		type     : 'customs',
		iconType : 'customs',
	},
	destination_fcl_customs: {
		tag      : 'FCL Customs',
		icon     : IcMCustoms,
		type     : 'customs',
		iconType : 'customs',
	},
	origin_lcl_customs: {
		tag      : 'LCL Customs',
		icon     : IcMCustoms,
		type     : 'customs',
		iconType : 'customs',
	},
	destination_lcl_customs: {
		tag      : 'LCL Customs',
		icon     : IcMCustoms,
		type     : 'customs',
		iconType : 'customs',
	},
	origin_air_customs: {
		tag      : 'Air Customs',
		icon     : IcMCustoms,
		type     : 'customs',
		iconType : 'customs',
	},
	destination_air_customs: {
		tag      : 'Air Customs',
		icon     : IcMCustoms,
		type     : 'customs',
		iconType : 'customs',

	},
	fcl_cfs: {
		tag      : 'FCL CFS',
		icon     : IcMCustoms,
		type     : 'customs',
		iconType : 'customs',

	},
	origin_fcl_cfs: {
		tag      : 'FCL CFS',
		icon     : IcMCustoms,
		type     : 'customs',
		iconType : 'customs',
	},
	destination_fcl_cfs: {
		tag      : 'FCL CFS',
		icon     : IcMCustoms,
		type     : 'customs',
		iconType : 'customs',
	},
	export_transportation: {
		tag      : 'Pickup',
		icon     : IcMFland,
		type     : 'land',
		iconType : 'truck',
	},
	export_fcl_customs: {
		tag      : 'Customs',
		icon     : IcMCustoms,
		type     : 'customs',
		iconType : 'customs',
	},
	import_fcl_customs: {
		tag      : 'Customs',
		icon     : IcMCustoms,
		type     : 'customs',
		iconType : 'customs',
	},
	export_lcl_customs: {
		tag      : 'Customs',
		icon     : IcMCustoms,
		type     : 'customs',
		iconType : 'customs',
	},
	import_lcl_customs: {
		tag      : 'Customs',
		icon     : IcMCustoms,
		type     : 'customs',
		iconType : 'customs',
	},
	export_air_customs: {
		tag      : 'Customs',
		icon     : IcMCustoms,
		type     : 'customs',
		iconType : 'customs',
	},
	import_air_customs: {
		tag      : 'Customs',
		icon     : IcMCustoms,
		type     : 'customs',
		iconType : 'customs',
	},
	import_haulage_freight: {
		tag      : 'Haulage',
		icon     : 'ic-train',
		type     : 'land',
		iconType : 'train',
	},
	export_haulage_freight: {
		tag      : 'Haulage',
		icon     : 'ic-train',
		type     : 'land',
		iconType : 'train',
	},
	import_transportation: {
		tag      : 'Drop',
		icon     : IcMFland,
		type     : 'land',
		iconType : 'truck',
	},
	destination_customs: {
		tag      : 'Customs',
		icon     : IcMCustoms,
		type     : 'customs',
		iconType : 'customs',
	},
	destination_haulage: {
		tag      : 'Haulage',
		icon     : 'ic-train',
		type     : 'land',
		iconType : 'train',
	},
	export_fcl_cfs: {
		tag      : 'CFS',
		icon     : IcMCustoms,
		type     : 'customs',
		iconType : 'customs',
	},
	import_fcl_cfs: {
		tag      : 'CFS',
		icon     : IcMCustoms,
		type     : 'customs',
		iconType : 'customs',
	},
	customs: {
		tag      : 'Customs',
		icon     : IcMCustoms,
		type     : 'customs',
		iconType : 'customs',
	},
	haulage: {
		tag      : 'Haulage',
		icon     : 'ic-train',
		type     : 'land',
		iconType : 'train',
	},
	ltl: {
		tag      : 'LTL',
		icon     : IcMFland,
		type     : 'land',
		iconType : 'truck',
	},
	ftl: {
		tag      : 'FTL',
		icon     : IcMFland,
		type     : 'land',
		iconType : 'truck',
	},
	trailer: {
		tag      : 'Trailer',
		icon     : IcMFland,
		type     : 'land',
		iconType : 'truck',
	},
};

export default MAPPING;
