const COMMODITY_MAPPING = {
	chilled                      : 'Chilled',
	consumer_durables            : 'Consumer Durables',
	consumer_durables_equipments : 'Consumer Durables Equipments',
	consumer_durables_equipments_machinery:
		'Consumer Durables Equipments Machinery',
	'corrosives-8'                        : 'Corrosives 8',
	cotton_and_yarn                       : 'Cotton and yarn',
	'emit_flammable_gases_with_water-4.3' : 'Emit Flammable Gases with Water 4.3',
	equipments_plant_machinery            : 'Equipments Plant Machinery',
	express                               : 'Express',
	fabric_and_textiles                   : 'Fabric and textiles',
	'flammable_liquids-3'                 : 'Flammable Liquids 3',
	'flammable_solids-4.1'                : 'Flammable Solids 4.1',
	'flammable_solids_self_heat-4.2'      : 'Flammable Solids 4.2',
	fmcg                                  : 'FCMG',
	fmcg_consumer_durables                : 'FCMG Consumer Durables',
	frozen                                : 'Frozen',
	'gases-2.1'                           : 'Gases 2.1',
	'gases-2.2'                           : 'Gases 2.2',
	'gases-2.3'                           : 'Gases 2.3',
	general                               : 'General',
	hazardous                             : 'Hazardous',
	'imo_classes-5.1'                     : 'IMO Classes 5.1',
	in_gauge_cargo                        : 'In Gauge Cargo',
	'infectious_substances-6.2'           : 'Infectious Substances 6.2',
	live_animals                          : 'Live animals',
	'miscellaneous_dangerous_goods-9'     : 'Miscellaneous dangerous goods 9',
	non_haz_gases                         : 'Non Hazardous Gases',
	non_haz_liquids                       : 'Non Hazardous Liquids',
	non_haz_solids                        : 'Non Hazardous Solids',
	perishable                            : 'Perishable',
	pharma                                : 'Pharma',
	pta                                   : 'PTA',
	'radioactive_material-7'              : 'Radioactive material 7',
	sugar_rice                            : 'Sugar Rice',
	'toxic_substances-6.1'                : 'Toxic Substances 6.1',
	white_goods                           : 'White Goods',
};

export default COMMODITY_MAPPING;
