const DESIGNATION = ({ t = () => {} }) => ({
	i_am_isc_bd_manager                  : t('settings:work_scopes_option_text_1'),
	i_am_president                       : t('settings:work_scopes_option_text_2'),
	i_am_exporter_head                   : t('settings:work_scopes_option_text_3'),
	i_am_accountant                      : t('settings:work_scopes_option_text_4'),
	i_am_business_development_consultant : t('settings:work_scopes_option_text_5'),
	i_am_signing_authority               : t('settings:work_scopes_option_text_6'),
	i_am_cfo                             : t('settings:work_scopes_option_text_7'),
	i_work_in_procurement                : t('settings:work_scopes_option_text_8'),
	i_work_in_operations                 : t('settings:work_scopes_option_text_9'),
	i_am_proprietor                      : t('settings:work_scopes_option_text_10'),
	i_am_managing_director               : t('settings:work_scopes_option_text_11'),
	other                                : t('settings:work_scopes_option_text_12'),
	i_am_owner                           : t('settings:work_scopes_option_text_13'),
	i_am_director                        : t('settings:work_scopes_option_text_14'),
	i_work_in_finance                    : t('settings:work_scopes_option_text_15'),
	i_am_sales_coordinator               : t('settings:work_scopes_option_text_16'),
	i_am_logistics_manager               : t('settings:work_scopes_option_text_17'),
	i_am_finance_manager                 : t('settings:work_scopes_option_text_18'),
	i_am_manager                         : t('settings:work_scopes_option_text_19'),
	i_am_branch_manager                  : t('settings:work_scopes_option_text_20'),
	i_am_finance_head                    : t('settings:work_scopes_option_text_21'),
	i_am_operation_head                  : t('settings:work_scopes_option_text_22'),
	i_work_in_marketing_and_sales        : t('settings:work_scopes_option_text_23'),
	i_am_business_development_manager    : t('settings:work_scopes_option_text_24'),
	i_am_partner                         : t('settings:work_scopes_option_text_25'),
	i_am_ceo                             : t('settings:work_scopes_option_text_26'),
});

export default DESIGNATION;
