const HIDE_LAYOUT = [
	'/login',
	'/forgot-password',
	'/reset-password/[id]',
	'/apply',
	'/api/getMetabaseUrl',
	'/api/get-content',
	'/url/[token]',
	'/verify-auto-sign-up-email/[token]',
	'/verify-auto-login/[token]',
	'/feedback/[feedback_id]/[css]',
	'/verify-microsoft-link',
	'/unsubscribe',
	'/verify-sign-up-saas/[token]',
	'/generate-outlook-token',
	'/get-started',
	'/signup',
	'/404',
	'/500',
	'/verify-email/[id]',
	'/raise-cancellation-ticket',
];
export default HIDE_LAYOUT;
