import {
	Modes,
	FCLControls,
	FCLServices,
	FCLServicesDetails,
	FCLEnquiryCreateControls,
	LCLEnquiryCreateControls,
	LCLControls,
	LCLServicesDetails,
	LCLServices,
	AirEnquiryCreateControls,
	AirControls,
	AirServicesDetails,
	AirServices,
	TrailerEnquiryCreateControls,
	TrailerControls,
	FTLEnquiryCreateControls,
	FTLControls,
	LTLEnquiryCreateControls,
	LTLControls,
	LCLCustomsEnquiryCreateControls,
	LCLCustomsControls,
	FCLCustomsEnquiryCreateControls,
	FCLCustomsControls,
	AirCustomsEnquiryCreateControls,
	AirCustomsControls,
	FCLHaulageEnquiryCreateControls,
	FCLHaulageControls,
	FClCFSEnquiryCreateControls,
} from '../../../configurations';
import domesticServiceDetails from '../../../configurations/search/domestic/domestic-service-details';
import domesticServices from '../../../configurations/search/domestic/domestic-services';

const getConfiguration = (type, mode) => {
	if (type === 'modes') {
		return Modes;
	}

	const configs = {
		fcl_freight_services                                   : FCLServices,
		'fcl_freight_search-controls'                          : FCLControls,
		'fcl_freight_service-details'                          : FCLServicesDetails,
		'fcl_freight_enquiry-create-controls'                  : FCLEnquiryCreateControls(),
		lcl_freight_services                                   : LCLServices,
		'lcl_freight_search-controls'                          : LCLControls,
		'lcl_freight_service-details'                          : LCLServicesDetails,
		'lcl_freight_enquiry-create-controls'                  : LCLEnquiryCreateControls(),
		air_freight_services                                   : AirServices,
		'air_freight_search-controls'                          : AirControls,
		'air_freight_service-details'                          : AirServicesDetails,
		'air_freight_enquiry-create-controls'                  : AirEnquiryCreateControls(),
		trailer_freight_services                               : domesticServices.trailer_freight,
		'trailer_freight_search-controls'                      : TrailerControls,
		'trailer_freight_service-origin-pickup-controls'       : [],
		'trailer_freight_service-origin-customs-controls'      : [],
		'trailer_freight_service-destination-drop-controls'    : [],
		'trailer_freight_service-destination-customs-controls' : [],
		'trailer_freight_service-details'                      : domesticServiceDetails.trailer_freight,
		'trailer_freight_enquiry-create-controls'              : TrailerEnquiryCreateControls(),
		ftl_freight_services                                   : domesticServices.ftl_freight,
		'ftl_freight_search-controls'                          : FTLControls,
		'ftl_freight_service-origin-pickup-controls'           : [],
		'ftl_freight_service-origin-customs-controls'          : [],
		'ftl_freight_service-destination-drop-controls'        : [],
		'ftl_freight_service-destination-customs-controls'     : [],
		'ftl_freight_service-details'                          : domesticServiceDetails.ftl_freight,
		'ftl_freight_enquiry-create-controls'                  : FTLEnquiryCreateControls(),
		ltl_freight_services                                   : domesticServices.ltl_freight,
		'ltl_freight_search-controls'                          : LTLControls,
		'ltl_freight_service-origin-pickup-controls'           : [],
		'ltl_freight_service-origin-customs-controls'          : [],
		'ltl_freight_service-destination-drop-controls'        : [],
		'ltl_freight_service-destination-customs-controls'     : [],
		'ltl_freight_service-details'                          : domesticServiceDetails.ltl_freight,
		'ltl_freight_enquiry-create-controls'                  : LTLEnquiryCreateControls(),
		lcl_customs_services                                   : domesticServices.lcl_customs,
		'lcl_customs_search-controls'                          : LCLCustomsControls,
		'lcl_customs_service-origin-pickup-controls'           : [],
		'lcl_customs_service-origin-customs-controls'          : [],
		'lcl_customs_service-destination-drop-controls'        : [],
		'lcl_customs_service-destination-customs-controls'     : [],
		'lcl_customs_service-details'                          : domesticServiceDetails.lcl_customs,
		'lcl_customs_enquiry-create-controls'                  : LCLCustomsEnquiryCreateControls(),
		fcl_customs_services                                   : domesticServices.fcl_customs,
		'fcl_customs_search-controls'                          : FCLCustomsControls,
		'fcl_customs_service-origin-pickup-controls'           : [],
		'fcl_customs_service-origin-customs-controls'          : [],
		'fcl_customs_service-destination-drop-controls'        : [],
		'fcl_customs_service-destination-customs-controls'     : [],
		'fcl_customs_service-details'                          : domesticServiceDetails.fcl_customs,
		'fcl_customs_enquiry-create-controls'                  : FCLCustomsEnquiryCreateControls(),
		air_customs_services                                   : domesticServices.air_customs,
		'air_customs_search-controls'                          : AirCustomsControls,
		'air_customs_service-origin-pickup-controls'           : [],
		'air_customs_service-origin-customs-controls'          : [],
		'air_customs_service-destination-drop-controls'        : [],
		'air_customs_service-destination-customs-controls'     : [],
		'air_customs_service-details'                          : domesticServiceDetails.air_customs,
		'air_customs_enquiry-create-controls'                  : AirCustomsEnquiryCreateControls(),
		haulage_freight_services                               : domesticServices.haulage_freight,
		'haulage_freight_search-controls'                      : FCLHaulageControls,
		'haulage_freight_service-origin-pickup-controls'       : [],
		'haulage_freight_service-origin-customs-controls'      : [],
		'haulage_freight_service-destination-drop-controls'    : [],
		'haulage_freight_service-destination-customs-controls' : [],
		'haulage_freight_service-details'                      : domesticServiceDetails.haulage_freight,
		'haulage_freight_enquiry-create-controls':
			FCLHaulageEnquiryCreateControls(),
		'fcl_cfs_enquiry-create-controls': FClCFSEnquiryCreateControls(),
	};

	return configs[`${mode}_${type}`] || [];
};

export default getConfiguration;
