const MILESTONE_TYPES = {
	EMPTY_CONTAINER_PICKUP : 'Empty Container Pickup',
	TOLL_PLAZA_CROSSED     : 'Toll Plaza Crossed',
	STATION_CROSSED        : 'Station Crossed',
	LOADED_ON_RAIL         : 'Loaded on Rail',
	RAIL_DEPARTURE         : 'Rail Departure',
	RAIL_ARRIVAL           : 'Rail Arrival',
	UNLOADED_FROM_RAIL     : 'Unloaded from Rail',
	LOADED_ON_VESSEL       : 'Loaded on Vessel',
	VESSEL_DEPARTURE       : 'Vessel Departure',
	VESSEL_IN_TRANSIT      : 'Vessel in Transit',
	VESSEL_ARRIVAL         : 'Vessel Arrival',
	UNLOAD_FROM_VESSEL     : 'Unload from Vessel',
	GATE_OUT               : 'Gate Out',
	GATE_IN                : 'Gate In',
	CARRIER_RELEASE        : 'Carrier Release',
	DELIVERY               : 'Delivery',
	EMPTY_CONTAINER_RETURN : 'Empty Container Return',
	CFS_OUT                : 'CFS Out',
	CFS_IN                 : 'CFS In',
};

const UNSHADED_MILESTONES = [
	MILESTONE_TYPES.STATION_CROSSED,
	MILESTONE_TYPES.TOLL_PLAZA_CROSSED,
];

export const list = [
	{
		tracking_data: [
			{
				id                         : '6bd47b38-35fb-4a80-9f81-fef50c029838',
				saas_container_timeline_id : '22390d35-465f-4605-a8f4-32a81708d2e7',
				milestone                  : 'Empty Container pickup',
				milestone_metadata         : null,
				transport_mode             : '',
				vessel_name                : '',
				voyage_no                  : '',
				location                   : 'NHAVA SHEVA',
				latitude                   : null,
				longitude                  : null,
				event_date                 : '2021-08-31T22:51:00.000Z',
				alert_name                 : null,
				alert_level                : null,
				alert_action               : null,
				alert_details              : null,
				sequence                   : 1,
			},
			{
				id                         : 'e5b3fb43-f4f6-4ef5-be47-c092807596f6',
				saas_container_timeline_id : '22390d35-465f-4605-a8f4-32a81708d2e7',
				milestone                  : 'Gate',
				milestone_metadata         : [],
				transport_mode             : '',
				vessel_name                : 'COSCO JAPAN',
				voyage_no                  : '0PE1XW1MA',
				location                   : 'NHAVA SHEVA',
				latitude                   : null,
				longitude                  : null,
				event_date                 : '2021-09-13T18:48:00.000Z',
				alert_name                 : null,
				alert_level                : null,
				alert_action               : null,
				alert_details              : null,
				sequence                   : 2,
			},
			{
				id                         : '50812548-8c33-4b8b-b484-b2229c2ff3e9',
				saas_container_timeline_id : '22390d35-465f-4605-a8f4-32a81708d2e7',
				milestone                  : 'Loaded on vessel and ready to depart',
				milestone_metadata         : null,
				transport_mode             : '',
				vessel_name                : 'COSCO JAPAN',
				voyage_no                  : '0PE1XW1MA',
				location                   : 'NHAVA SHEVA',
				latitude                   : null,
				longitude                  : null,
				event_date                 : '2021-09-16T02:31:00.000Z',
				alert_name                 : null,
				alert_level                : null,
				alert_action               : null,
				alert_details              : null,
				sequence                   : 3,
			},
			{
				id                         : '36deec45-970d-4379-b7db-d3167d36095b',
				saas_container_timeline_id : '22390d35-465f-4605-a8f4-32a81708d2e7',
				milestone                  : 'Discharged in transhipment',
				milestone_metadata         : null,
				transport_mode             : '',
				vessel_name                : 'COSCO JAPAN',
				voyage_no                  : '0PE1XW1MA',
				location                   : 'TANGER MED',
				latitude                   : null,
				longitude                  : null,
				event_date                 : '2021-10-01T19:49:00.000Z',
				alert_name                 : null,
				alert_level                : null,
				alert_action               : null,
				alert_details              : null,
				sequence                   : 4,
			},
			{
				id                         : 'b40fb8f0-50d6-4a9a-8e52-72b96a2f5ad7',
				saas_container_timeline_id : '22390d35-465f-4605-a8f4-32a81708d2e7',
				milestone                  : 'Loaded on vessel and ready to depart',
				milestone_metadata         : null,
				transport_mode             : '',
				vessel_name                : 'CMA CGM RIO GRANDE',
				voyage_no                  : '0NSA7S1MA',
				location                   : 'TANGER MED',
				latitude                   : null,
				longitude                  : null,
				event_date                 : '2021-10-08T05:41:00.000Z',
				alert_name                 : null,
				alert_level                : null,
				alert_action               : null,
				alert_details              : null,
				sequence                   : 5,
			},
			{
				id                         : 'ac33327f-7e69-41c1-bcce-5f6401edfe61',
				saas_container_timeline_id : '22390d35-465f-4605-a8f4-32a81708d2e7',
				milestone                  : 'Vessel Arrival',
				milestone_metadata         : null,
				transport_mode             : '',
				vessel_name                : 'CMA CGM RIO GRANDE',
				voyage_no                  : '0NSA7S1MA',
				location                   : 'ITAJAI',
				latitude                   : null,
				longitude                  : null,
				event_date                 : '2021-10-30T07:00:00.000Z',
				alert_name                 : null,
				alert_level                : null,
				alert_action               : null,
				alert_details              : null,
				sequence                   : 6,
			},
			{
				id                         : 'd425b490-4ea2-4e4f-941d-e34d9eb71127',
				saas_container_timeline_id : '22390d35-465f-4605-a8f4-32a81708d2e7',
				milestone                  : 'Arrived and Unloaded from vessel',
				milestone_metadata         : null,
				transport_mode             : '',
				vessel_name                : 'CMA CGM RIO GRANDE',
				voyage_no                  : '0NSA8N1MA',
				location                   : 'ITAJAI',
				latitude                   : null,
				longitude                  : null,
				event_date                 : '2021-10-31T04:31:00.000Z',
				alert_name                 : null,
				alert_level                : null,
				alert_action               : null,
				alert_details              : null,
				sequence                   : 7,
			},
			{
				id                         : '379fcc04-b908-4731-a358-6a080064dd08',
				saas_container_timeline_id : '22390d35-465f-4605-a8f4-32a81708d2e7',
				milestone                  : 'Gate',
				milestone_metadata         : [],
				transport_mode             : '',
				vessel_name                : 'CMA CGM RIO GRANDE',
				voyage_no                  : '0NSA8N1MA',
				location                   : 'ITAJAI',
				latitude                   : null,
				longitude                  : null,
				event_date                 : '2021-11-01T10:25:00.000Z',
				alert_name                 : null,
				alert_level                : null,
				alert_action               : null,
				alert_details              : null,
				sequence                   : 8,
			},
		],
	},
	{
		tracking_data: [
			{
				id                         : 'e5b3fb43-f4f6-4ef5-be47-c092807596f6',
				saas_container_timeline_id : '22390d35-465f-4605-a8f4-32a81708d2e7',
				milestone                  : 'Gate',
				milestone_metadata         : [],
				transport_mode             : '',
				vessel_name                : 'COSCO JAPAN',
				voyage_no                  : '0PE1XW1MA',
				location                   : 'NHAVA SHEVA',
				latitude                   : null,
				longitude                  : null,
				event_date                 : '2021-09-13T18:48:00.000Z',
				alert_name                 : null,
				alert_level                : null,
				alert_action               : null,
				alert_details              : null,
				sequence                   : 2,
			},
			{
				id                         : '50812548-8c33-4b8b-b484-b2229c2ff3e9',
				saas_container_timeline_id : '22390d35-465f-4605-a8f4-32a81708d2e7',
				milestone                  : 'Loaded on vessel and ready to depart',
				milestone_metadata         : null,
				transport_mode             : '',
				vessel_name                : 'COSCO JAPAN',
				voyage_no                  : '0PE1XW1MA',
				location                   : 'NHAVA SHEVA',
				latitude                   : null,
				longitude                  : null,
				event_date                 : '2021-09-16T02:31:00.000Z',
				alert_name                 : null,
				alert_level                : null,
				alert_action               : null,
				alert_details              : null,
				sequence                   : 3,
			},
			{
				id                         : '36deec45-970d-4379-b7db-d3167d36095b',
				saas_container_timeline_id : '22390d35-465f-4605-a8f4-32a81708d2e7',
				milestone                  : 'Discharged in transhipment',
				milestone_metadata         : null,
				transport_mode             : '',
				vessel_name                : 'COSCO JAPAN',
				voyage_no                  : '0PE1XW1MA',
				location                   : 'TANGER MED',
				latitude                   : null,
				longitude                  : null,
				event_date                 : '2021-10-01T19:49:00.000Z',
				alert_name                 : null,
				alert_level                : null,
				alert_action               : null,
				alert_details              : null,
				sequence                   : 4,
			},
			{
				id                         : 'b40fb8f0-50d6-4a9a-8e52-72b96a2f5ad7',
				saas_container_timeline_id : '22390d35-465f-4605-a8f4-32a81708d2e7',
				milestone                  : 'Loaded on vessel and ready to depart',
				milestone_metadata         : null,
				transport_mode             : '',
				vessel_name                : 'CMA CGM RIO GRANDE',
				voyage_no                  : '0NSA7S1MA',
				location                   : 'TANGER MED',
				latitude                   : null,
				longitude                  : null,
				event_date                 : '2021-10-08T05:41:00.000Z',
				alert_name                 : null,
				alert_level                : null,
				alert_action               : null,
				alert_details              : null,
				sequence                   : 5,
			},
			{
				id                         : 'ac33327f-7e69-41c1-bcce-5f6401edfe61',
				saas_container_timeline_id : '22390d35-465f-4605-a8f4-32a81708d2e7',
				milestone                  : 'Vessel Arrival',
				milestone_metadata         : null,
				transport_mode             : '',
				vessel_name                : 'CMA CGM RIO GRANDE',
				voyage_no                  : '0NSA7S1MA',
				location                   : 'ITAJAI',
				latitude                   : null,
				longitude                  : null,
				event_date                 : '2021-10-30T07:00:00.000Z',
				alert_name                 : null,
				alert_level                : null,
				alert_action               : null,
				alert_details              : null,
				sequence                   : 6,
			},
			{
				id                         : 'd425b490-4ea2-4e4f-941d-e34d9eb71127',
				saas_container_timeline_id : '22390d35-465f-4605-a8f4-32a81708d2e7',
				milestone                  : 'Arrived and Unloaded from vessel',
				milestone_metadata         : null,
				transport_mode             : '',
				vessel_name                : 'CMA CGM RIO GRANDE',
				voyage_no                  : '0NSA8N1MA',
				location                   : 'ITAJAI',
				latitude                   : null,
				longitude                  : null,
				event_date                 : '2021-10-31T04:31:00.000Z',
				alert_name                 : null,
				alert_level                : null,
				alert_action               : null,
				alert_details              : null,
				sequence                   : 7,
			},
			{
				id                         : '379fcc04-b908-4731-a358-6a080064dd08',
				saas_container_timeline_id : '22390d35-465f-4605-a8f4-32a81708d2e7',
				milestone                  : 'Gate',
				milestone_metadata         : [],
				transport_mode             : '',
				vessel_name                : 'CMA CGM RIO GRANDE',
				voyage_no                  : '0NSA8N1MA',
				location                   : 'ITAJAI',
				latitude                   : null,
				longitude                  : null,
				event_date                 : '2021-11-01T10:25:00.000Z',
				alert_name                 : null,
				alert_level                : null,
				alert_action               : null,
				alert_details              : null,
				sequence                   : 8,
			},
		],
	},
	{
		tracking_data: [
			{
				id                         : '36deec45-970d-4379-b7db-d3167d36095b',
				saas_container_timeline_id : '22390d35-465f-4605-a8f4-32a81708d2e7',
				milestone                  : 'Discharged in transhipment',
				milestone_metadata         : null,
				transport_mode             : '',
				vessel_name                : 'COSCO JAPAN',
				voyage_no                  : '0PE1XW1MA',
				location                   : 'TANGER MED',
				latitude                   : null,
				longitude                  : null,
				event_date                 : '2021-10-01T19:49:00.000Z',
				alert_name                 : null,
				alert_level                : null,
				alert_action               : null,
				alert_details              : null,
				sequence                   : 4,
			},
			{
				id                         : 'b40fb8f0-50d6-4a9a-8e52-72b96a2f5ad7',
				saas_container_timeline_id : '22390d35-465f-4605-a8f4-32a81708d2e7',
				milestone                  : 'Loaded on vessel and ready to depart',
				milestone_metadata         : null,
				transport_mode             : '',
				vessel_name                : 'CMA CGM RIO GRANDE',
				voyage_no                  : '0NSA7S1MA',
				location                   : 'TANGER MED',
				latitude                   : null,
				longitude                  : null,
				event_date                 : '2021-10-08T05:41:00.000Z',
				alert_name                 : null,
				alert_level                : null,
				alert_action               : null,
				alert_details              : null,
				sequence                   : 5,
			},
			{
				id                         : 'ac33327f-7e69-41c1-bcce-5f6401edfe61',
				saas_container_timeline_id : '22390d35-465f-4605-a8f4-32a81708d2e7',
				milestone                  : 'Vessel Arrival',
				milestone_metadata         : null,
				transport_mode             : '',
				vessel_name                : 'CMA CGM RIO GRANDE',
				voyage_no                  : '0NSA7S1MA',
				location                   : 'ITAJAI',
				latitude                   : null,
				longitude                  : null,
				event_date                 : '2021-10-30T07:00:00.000Z',
				alert_name                 : null,
				alert_level                : null,
				alert_action               : null,
				alert_details              : null,
				sequence                   : 6,
			},
			{
				id                         : 'd425b490-4ea2-4e4f-941d-e34d9eb71127',
				saas_container_timeline_id : '22390d35-465f-4605-a8f4-32a81708d2e7',
				milestone                  : 'Arrived and Unloaded from vessel',
				milestone_metadata         : null,
				transport_mode             : '',
				vessel_name                : 'CMA CGM RIO GRANDE',
				voyage_no                  : '0NSA8N1MA',
				location                   : 'ITAJAI',
				latitude                   : null,
				longitude                  : null,
				event_date                 : '2021-10-31T04:31:00.000Z',
				alert_name                 : null,
				alert_level                : null,
				alert_action               : null,
				alert_details              : null,
				sequence                   : 7,
			},
			{
				id                         : '379fcc04-b908-4731-a358-6a080064dd08',
				saas_container_timeline_id : '22390d35-465f-4605-a8f4-32a81708d2e7',
				milestone                  : 'Gate',
				milestone_metadata         : [],
				transport_mode             : '',
				vessel_name                : 'CMA CGM RIO GRANDE',
				voyage_no                  : '0NSA8N1MA',
				location                   : 'ITAJAI',
				latitude                   : null,
				longitude                  : null,
				event_date                 : '2021-11-01T10:25:00.000Z',
				alert_name                 : null,
				alert_level                : null,
				alert_action               : null,
				alert_details              : null,
				sequence                   : 8,
			},
		],
	},
];

export { UNSHADED_MILESTONES };
