import msds from './msds';
import shipping_surcharges from './shipping-surcharges';
import tech_supply_chain from './tech-supply-chain';
import best_practices_ltl from './best-practices-ltl';
import friendshoring from './friendshoring';
import ev_at_india_auto_expo_2_0_2_3 from './ev-at-india-auto-expo-_2_0_2_3';
import ways_to_save_in_global_supply_chain from './ways-to-save-in-global-supply-chain';
import top_5_business_trends_2_0_2_3 from './top-_5-business-trends-_2_0_2_3';
import consolidation_and_deconsolidation from './consolidation-and-deconsolidation';
import cargo_ready_date from './cargo-ready-date';
import import_general_manifest from './import-general-manifest';
import currency_adjustment_factor from './currency-adjustment-factor';
import global_shipping_alliances from './global-shipping-alliances';
import _2_0_2_2_year_in_review from './_2_0_2_2-year-in-review';
import indian_economy_november_2_0_2_2 from './indian-economy-november-_2_0_2_2';
import switch_bl from './switch-bl';
import bullwhip_effect from './bullwhip-effect';
import _3_pl from './_3pl';
import milk_run from './milk-run';
import multi_modal_logistics_india from './multi-modal-logistics-india';
const blogs = [msds,shipping_surcharges,tech_supply_chain,best_practices_ltl,friendshoring,ev_at_india_auto_expo_2_0_2_3,ways_to_save_in_global_supply_chain,top_5_business_trends_2_0_2_3,consolidation_and_deconsolidation,cargo_ready_date,import_general_manifest,currency_adjustment_factor,global_shipping_alliances,_2_0_2_2_year_in_review,indian_economy_november_2_0_2_2,switch_bl,bullwhip_effect,_3_pl,milk_run,multi_modal_logistics_india];

export default blogs;