export const commoditiesMapping = {
	fcl_freight: {
		standard: [
			'general',
			'white_goods',
			'pta',
			'agro',
			'cotton_and_yarn',
			'fabric_and_textiles',
			'raw_cotton',
			'rice_bran',
			'sugar_rice',
			'gases-2.1',
			'gases-2.2',
			'gases-2.3',
			'flammable_liquids-3',
			'flammable_solids-4.1',
			'flammable_solids_self_heat-4.2',
			'emit_flammable_gases_with_water-4.3',
			'imo_classes-5.1',
			'toxic_substances-6.1',
			'infectious_substances-6.2',
			'radioactive_material-7',
			'corrosives-8',
			'miscellaneous_dangerous_goods-9',
		],

		refer: [
			'chilled',
			'frozen',
			'pharma',
			'meat',
			'sea_food',
			'fruits_and_veg',
		],

		open_top: ['in_gauge_cargo'],

		open_side: ['general'],

		flat_rack: ['in_gauge_cargo'],

		iso_tank: [
			'non_haz_solids',
			'non_haz_liquids',
			'non_haz_gases',
			'gases-2.1',
			'gases-2.2',
			'gases-2.3',
			'flammable_liquids-3',
			'flammable_solids-4.1',
			'flammable_solids_self_heat-4.2',
			'emit_flammable_gases_with_water-4.3',
			'imo_classes-5.1',
			'toxic_substances-6.1',
			'infectious_substances-6.2',
			'radioactive_material-7',
			'corrosives-8',
			'miscellaneous_dangerous_goods-9',
		],

	},

	lcl_freight: [
		'general',
		'gases-2.1',
		'gases-2.2',
		'gases-2.3',
		'flammable_liquids-3',
		'flammable_solids-4.1',
		'flammable_solids_self_heat-4.2',
		'emit_flammable_gases_with_water-4.3',
		'imo_classes-5.1',
		'toxic_substances-6.1',
		'infectious_substances-6.2',
		'radioactive_material-7',
		'corrosives-8',
		'miscellaneous_dangerous_goods-9',
	],

	air_freight: [
		'general',
		'perishable',
		'live_animals',
		'pharma',
		'harzardous',
		'express',
	],
};
