const IMAGE_URLS = {
	cogoport_logo        : 'https://cdn.cogoport.io/cms-prod/cogo_app/vault/original/cogoport.svg',
	iec_red_flag         : 'https://cdn.cogoport.io/cms-prod/cogo_app/vault/original/redFlag.svg',
	iec_green_flag       : 'https://cdn.cogoport.io/cms-prod/cogo_app/vault/original/greenflag.svg',
	iec_yellow_flag      : 'https://cdn.cogoport.io/cms-prod/cogo_app/vault/original/yellwflag.svg',
	coin_bag_image       : 'https://cdn.cogoport.io/cms-prod/cogo_app/vault/original/CogoBag.png',
	cart_image           : 'https://cdn.cogoport.io/cms-prod/cogo_app/vault/original/Cart-Outline (1).png',
	succes_image         : 'https://cdn.cogoport.io/cms-prod/cogo_app/vault/original/exclamation.svg',
	empty_image          : 'https://cdn.cogoport.io/cms-prod/cogo_app/vault/original/undraw_empty_cart_co35.svg',
	category_image       : 'https://cdn.cogoport.io/cms-prod/cogo_app/vault/original/cogo_logo_white_bg.svg',
	empty_category_image : 'https://cdn.cogoport.io/cms-prod/cogo_app/vault/original/no category',
	empty_details_image  : 'https://cdn.cogoport.io/cms-prod/cogo_admin/vault/original/shipmentEmptyState.png',
	send_gift_image      : 'https://cdn.cogoport.io/cms-prod/cogo_app/vault/original/send.gif',
	banner_image         : 'https://cdn.cogoport.io/cms-prod/cogo_app/vault/original/Banner 1.png',
	signatory_image      : 'https://cdn.cogoport.io/cms-prod/cogo_partner/vault/original/Vector.png',
	edit_image:
        'https://cdn.cogoport.io/cms-prod/cogo_partner/vault/original/animation_500_lhvo6uhx1.png',
	yellow_vessel            : 'https://cdn.cogoport.io/cms-prod/cogo_app/vault/original/shipYellow.png',
	red_vessel               : 'https://cdn.cogoport.io/cms-prod/cogo_app/vault/original/shipRed.png',
	black_vessel             : 'https://cdn.cogoport.io/cms-prod/cogo_app/vault/original/shipArrow.png',
	loading                  : 'https://cdn.cogoport.io/cms-prod/cogo_app/vault/original/loading.svg',
	loading_banner           : 'https://cdn.cogoport.io/cms-prod/cogo_app/vault/original/loading-banner.svg',
	air_empty_state          : 'https://cdn.cogoport.io/cms-prod/cogo_app/vault/original/air-connect.svg',
	ocean_empty_state        : 'https://cdn.cogoport.io/cms-prod/cogo_app/vault/original/ship-cargo.jpg',
	origin_map_pointer       : 'https://cdn.cogoport.io/cms-prod/cogo_app/vault/original/map_origin.svg',
	destination_map_pointer  : 'https://cdn.cogoport.io/cms-prod/cogo_app/vault/original/map_destination.svg',
	map_loading              : 'https://cogoport-maps.s3.ap-south-1.amazonaws.com/world+(2).svg',
	empty_state_finder       : 'https://cdn.cogoport.io/cms-prod/cogo_app/vault/original/ic-empty-doc_app.svg',
	ship_icon                : 'https://cdn.cogoport.io/cms-prod/cogo_app/vault/original/shipIcon.jpg',
	truck_icon               : 'https://cdn.cogoport.io/cms-prod/cogo_app/vault/original/truckIcon.png',
	air_icon2                : 'https://cdn.cogoport.io/cms-prod/cogo_app/vault/original/airplane.png',
	tracking_loader          : 'https://cdn.cogoport.io/cms-prod/cogo_app/vault/original/cogo-animation.gif',
	extract_data             : 'https://cdn.cogoport.io/cms-prod/cogo_app/vault/original/Data-extraction.jpg',
	container_icon           : 'https://cdn.cogoport.io/cms-prod/cogo_app/vault/original/icdport.svg',
	air_icon                 : 'https://cdn.cogoport.io/cms-prod/cogo_admin/vault/original/airicon.svg',
	unsubscription_cargo     : 'https://cdn.cogoport.io/cms-prod/cogo_app/vault/original/page_cargo.png',
	unsubscription_bottle    : 'https://cdn.cogoport.io/cms-prod/cogo_app/vault/original/Bottle.png',
	unsubscription_plane     : 'https://cdn.cogoport.io/cms-prod/cogo_app/vault/original/page_plane.png',
	insurance_empty_image    : 'https://cdn.cogoport.io/cms-prod/cogo_app/vault/original/Insurance.png',
	kyc_dialog_image         : 'https://cdn.cogoport.io/cms-prod/cogo_app/vault/original/nogstIcon.svg',
	secure_icon              : 'https://cdn.cogoport.io/cms-prod/cogo_app/vault/original/secure-icon.svg',
	heading_icon             : 'https://cdn.cogoport.io/cms-prod/cogo_app/vault/original/heading.svg',
	sub_heading_icon         : 'https://cdn.cogoport.io/cms-prod/cogo_app/vault/original/subheading.svg',
	loading_icon             : 'https://cdn.cogoport.io/cms-prod/cogo_app/vault/original/loading.svg',
	no_data_icon             : 'https://cdn.cogoport.io/cms-prod/cogo_app/vault/original/nodata.svg',
	payment_icon             : 'https://cdn.cogoport.io/cms-prod/cogo_app/vault/original/payment.svg',
	secure_profile_icon      : 'https://cdn.cogoport.io/cms-prod/cogo_app/vault/original/secure-profile-icon.svg',
	no_schedules_found_image : 'https://cdn.cogoport.io/cms-prod/cogo_app/vault/original/empty_icon 1.svg',
	archive_icon             : 'https://cdn.cogoport.io/cms-prod/cogo_app/vault/original/archive.svg',
	empty_state              : 'https://cdn.cogoport.io/cms-prod/cogo_app/vault/original/empty_icon 1.svg',
	globe                    : 'https://cdn.cogoport.io/cms-prod/cogo_partner/vault/original/globe-language.png',
	cogoport_image:
	'https://cogoport-production.sgp1.digitaloceanspaces.com/e845419ea5eacebda858bad8b20d2797/cogoport-logo.svg',
	pen_image        : 'https://cdn.cogoport.io/cms-prod/cogo_admin/vault/original/tds-doc-icon.svg',
	premium_image    : 'https://cdn.cogoport.io/cms-prod/cogo_app/vault/original/crown_new.svg',
	loader           : 'https://cdn.cogoport.io/cms-prod/cogo_admin/vault/original/spinner.svg',
	document_icon    : 'https://cdn.cogoport.io/cms-prod/cogo_app/vault/original/document_icon.png',
	web_bot_icon     : 'https://cdn.cogoport.io/cms-prod/cogo_public/vault/original/web_bot',
	animated_web_bot : 'https://cdn.cogoport.io/cms-prod/cogo_public/vault/original/animated_bot.gif',
	track_image      : 'https://cdn.cogoport.io/cms-prod/cogo_admin/vault/original/delayClock.svg',
	clock_image      : 'https://cdn.cogoport.io/cms-prod/cogo_admin/vault/original/green_clock.svg',
	road_map_image   : 'https://cdn.cogoport.io/cms-prod/cogo_app/vault/original/road-map.svg',

};

export default IMAGE_URLS;
