name: Build

on:
  issue_comment:
    types: [created]

jobs:
  init:
    name: Init
    if: ${{ github.triggering_actor != 'dependabot[bot]' }} && github.event.issue.pull_request && (contains(github.event.comment.body, '/build') || contains(github.event.comment.body, '/checks'))
    uses: ./.github/workflows/reusable-run-setup.yml
    secrets: inherit
  
  build:
    if: github.event.issue.pull_request && (contains(github.event.comment.body, '/build') || contains(github.event.comment.body, '/checks'))
    needs: init
    uses: ./.github/workflows/comment-test-build.yml
    secrets: inherit