name: Build

on: [pull_request]

jobs:
  init:
    name: Init
    if: ${{ github.triggering_actor != 'dependabot[bot]' }}
    uses: ./.github/workflows/reusable-run-setup.yml
    secrets: inherit

  build:
    name: Test
    needs: init
    uses: ./.github/workflows/comment-test-build.yml
    secrets: inherit