name: Build
on:
  pull_request:
#   issue_comment:
#     types:
#       - created
jobs:
  build:
    name: Test Build
    # if: github.event.issue.pull_request && (contains(github.event.comment.body,
    #   '/build') || contains(github.event.comment.body, '/checks')) && ${{ always() }}
    runs-on: ubuntu-latest
    init:
      name: Init
      if: ${{ github.triggering_actor != 'dependabot[bot]' }}
      uses: ./.github/workflows/reusable-run-setup.yml
    build:
      name: Build
      needs: init
      uses: ./.github/workflows/comment-test-build.yml
    needs:
      - init
      - build