name: Lint
on:
  issue_comment:
    types:
      - created
jobs:
  lint:
    name: Test Lint
    if: github.event.issue.pull_request && (contains(github.event.comment.body,
      '/lint') || contains(github.event.comment.body, '/checks')) && ${{ always() }}
    runs-on: ubuntu-latest
    steps:
      - name: Init
        if: ${{ github.triggering_actor != 'dependabot[bot]' }}
        uses: ./.github/workflows/reusable-run-setup.yml
        secrets: inherit
      - name: Lint
        needs: init
        uses: ./.github/workflows/comment-test-lint.yml
        secrets: inherit
    needs:
      - init
      - lint