name: Lint

on:
  issue_comment:
    types: [created]

jobs:
  if: github.event.issue.pull_request && contains(github.event.comment.body, '/lint')

  init:
    name: Init
    if: ${{ github.triggering_actor != 'dependabot[bot]' }}
    uses: ./.github/workflows/reusable-run-setup.yml
    secrets: inherit
  
  lint:
    name: Test
    needs: init
    uses: ./.github/workflows/reusable-test-lint.yml
    secrets: inherit


  needs:
    - init # required to wait when the main job is done
    - lint # required to wait when the main job is done

  runs-on: ubuntu-latest

  if: ${{ always() }} # required to stop the runner even if the error happened in the previous jobs
