name: Lint
on: [pull_request]

jobs:
if: github.event.issue.pull_request && (contains(github.event.comment.body,'/build') || contains(github.event.comment.body, '/checks')) && ${{ always() }}
  init:
    name: Init
    if: ${{ github.triggering_actor != 'dependabot[bot]' }}
    uses: ./.github/workflows/reusable-run-setup.yml
    secrets: inherit
  
  lint:
    name: Test
    needs: init
    uses: ./.github/workflows/comment-test-lint.yml
    secrets: inherit
    